name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v6

      - name: Install Protobuf compiler
        run: sudo apt install -y protobuf-compiler

      - name: Build
        run: make

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuxedo-infinitybook-gen10
          path: target/release/tuxedo-infinitybook-gen10
